version: '3'

services:
  postgres:
    image: 'postgres:latest'
    container_name: postgres
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=jason
      - POSTGRES_PASSWORD="1234"
      - POSTGRES_DB=bug_tracker_test