name: fastapi-bug-tracker



on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

env:
  STAGE: testing
  WORKING_ON_PIPELINE: 'True'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip pipenv
          pipenv sync --dev
      
      - name: Lint tests (flake, black, isort)
        run: |
          # stop the build if there are Python syntax errors or undefined names
          pipenv run flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          pipenv run flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
          pipenv run black app --check
          pipenv run isort --check-only app
     
      - name: Mypy type checking
        run: |
          pipenv run mypy --check-untyped-defs -p app
      
      - name: Postgres container for integration + e2e testing
        run: |
          docker-compose -f "docker-compose-for-ci.yml" up -d --build
     
      - name: Test with pytest
        run: |
          pipenv run pytest