name: fastapi-bug-tracker



on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

env:
  STAGE: testing
  WORKING_ON_PIPELINE: 'True'
  POSTGRES_USER: jason
  POSTGRES_PASSWORD: '1234'
  POSTGRES_DB: bug_tracker_test

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip pipenv
          pipenv sync --dev
      
      - name: Lint tests + linting
        run: |
          pipenv run flake8 app --count --select=E9,F63,F7,F82 --show-source --statistics
          pipenv run flake8 app --count --exit-zero --max-line-length=120 --statistics
          pipenv run black app --check
          pipenv run isort --profile black --check-only app
     
      - name: Mypy type checking
        run: |
          pipenv run mypy --check-untyped-defs -p app
      
      - name: Postgres container for integration + e2e testing
        run: |
          docker-compose -f "docker-compose-for-ci.yml" up -d --build
     
      - name: Test with pytest
        run: |
          sleep 1
          pipenv run pytest